export const facts: string[] = [
    "Peter once ate 50 hot dogs in 10 minutes. He's still recovering.",
    "Peter once tried to fight a vending machine. The machine won.",
    "Peter once ran for mayor. His platform? Free beer for everyone!",
    "Peter once invented a new sandwich: the 'double-decker bacon pancake burger.'",
    "Peter’s spirit animal is a sloth… mostly because they both love naps.",
    "Peter once thought the moon was made of cheese, and he tried to eat it.",
    "Peter once confused a garage door opener for a TV remote for a week.",
    "Peter once built a robot out of junk parts, and it tried to overthrow him.",
    "Peter once got stuck in a bathtub for two days because he 'slipped on soap.'",
    "Peter once thought dinosaurs still existed because he saw one in a movie.",
    "Peter once tried to invent teleportation… but it just exploded.",
    "Peter once thought Lois was an alien because she 'didn’t like bacon.'",
    "Peter once claimed he could talk to birds, but all he did was squawk back.",
    "Peter once spent an entire day trying to invent invisible toast.",
    "Peter once thought 'YOLO' was an actual place and tried to visit it.",
    "Peter once tried to start a 'couch potato marathon.' He didn’t win.",
    "Peter once thought a fax machine was a time machine. Spoiler: It wasn’t.",
    "Peter once tried to climb Mount Everest… by walking up the stairs repeatedly.",
    "Peter once tried to fight gravity, claiming it was 'unfair.'",
    "Peter once mistook a fire alarm for a jukebox and tried to dance to it.",
    "Peter once got banned from the zoo for challenging a gorilla to arm-wrestle.",
    "Peter once tried to sell air on eBay… and almost succeeded.",
    "Peter once thought Wi-Fi was a new kind of sandwich.",
    "Peter once mistook a microwave for a TV and watched it for hours.",
    "Peter once tried to teach himself how to fly… by jumping off the couch.",
    "Peter once thought 'Ctrl+Alt+Delete' was a type of martial art.",
    "Peter once tried to declare his backyard an independent country.",
    "Peter once spent a whole day trying to figure out how mirrors work.",
    "Peter once thought the North Pole was a giant candy cane factory.",
    "Peter once tried to ride a dolphin like a horse. It did not end well.",
    "Peter once thought the ocean was just a really big swimming pool.",
    "Peter once claimed he invented a new color. It was just brown.",
    "Peter once tried to order pizza with a banana, thinking it was a phone.",
    "Peter once tried to dig to China using only a spoon.",
    "Peter once challenged a squirrel to a staring contest. He lost.",
    "Peter once mistook his own reflection for an intruder.",
    "Peter once tried to grow a tree by planting a pizza slice in the ground.",
    "Peter once spent hours trying to figure out how to open a childproof bottle.",
    "Peter once got lost in his own house for three hours.",
    "Peter once thought clouds were made of cotton candy and tried to eat one.",
    "Peter once tried to start a 'nap competition.' He was the only participant.",
    "Peter once mistook a watermelon for a football and kicked it.",
    "Peter once tried to prove he could communicate with dogs by barking at them.",
    "Peter once thought the Internet was an actual net you could catch fish with.",
    "Peter once tried to invent square wheels to 'make cars more interesting.'",
    "Peter once thought lightning was the sky taking pictures of him.",
    "Peter once tried to domesticate a squirrel. It ran away… with his lunch."
  ];
  