export const insults: string[] = [
    "You're like a pizza with no toppings—just plain dough!",
    "I've met houseplants with more ambition than you.",
    "If common sense was a currency, you'd be broke.",
    "Your brain's like a phone—always out of service.",
    "You're about as useful as a screen door on a submarine.",
    "I've seen sloths with better work ethics than you.",
    "You could be replaced by a slightly smarter rock.",
    "You're as sharp as a marble.",
    "Your elevator doesn't go all the way to the top floor, does it?",
    "You have the personality of a wet napkin.",
    "You're like a cloud—when you disappear, it's a beautiful day.",
    "You're not dumb; you're just... 'special.'",
    "You remind me of a black hole—all you do is suck the fun out of the room.",
    "I've seen better reflexes in a dead cat.",
    "You're the reason they put instructions on shampoo bottles.",
    "You're like a software bug—annoying and hard to get rid of.",
    "I bet if you had a brain cell, it would be lonely.",
    "You couldn’t find your way out of a paper bag with both hands.",
    "You have the charisma of a damp sponge.",
    "You're like a broken pencil—pointless.",
    "You're about as useful as a one-legged man in a butt-kicking contest.",
    "You have the social skills of a potato.",
    "Your intelligence is like a highway—there are a lot of exits.",
    "You're living proof that evolution can go in reverse.",
    "You're the human version of a participation trophy.",
    "You're like a light bulb—dim and not very bright.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "You're the reason there are warning labels on everything.",
    "You're like a Wi-Fi signal—weak and unreliable.",
    "You couldn’t pour water out of a boot with instructions on the heel.",
    "You’re about as useful as a chocolate teapot.",
    "Your brain’s still buffering… and has been for years.",
    "You’re not just a clown, you’re the whole circus.",
    "If you were any slower, you’d be going backward.",
    "You're like a broken GPS—you never know where you’re going.",
    "You have the emotional depth of a puddle.",
    "You’re as bright as a burnt-out lightbulb.",
    "You're as relevant as a VHS tape.",
    "You're the human equivalent of a typo.",
    "You're like an overcooked noodle—limp and useless.",
    "You’re the kind of person who claps when the plane lands.",
    "You're about as helpful as a screen on a motorcycle.",
    "You're like a bad haircut—everyone notices, but nobody says anything.",
    "If brains were dynamite, you wouldn’t have enough to blow your nose.",
    "You have the mental agility of a soap dish.",
    "You're like a speed bump—useless and only there to slow everyone down.",
    "You're the human version of autocorrect—always wrong, but thinking you're right.",
    "You're as useful as a pogo stick in quicksand.",
    "You're the reason we can't have nice things."
  ];
  