export const wisdom = [
    "The lesson here is: never try.",
    "Remember, if something's hard to do, it's not worth doing. Heh heh.",
    "Why do today what you can do tomorrow?",
    "I can't leave, I'm watching something important. Heh heh, it's a fly.",
    "You miss 100% of the beers you don't drink.",
    "Roads? Where we’re going, we don’t need roads… just wings and beers.",
    "Hey, remember when I took that test? Well, turns out I’m the world’s smartest man… according to me.",
    "The key to life is to never try too hard, unless it's for pie.",
    "You know what they say: happy wife, happy life… or something like that.",
    "Live every day like it's Taco Tuesday.",
    "A penny saved is a penny that will probably be spent on beer later.",
    "When life gives you lemons, make a lemon-flavored beer.",
    "You can’t put a price on happiness. Unless it’s beer, then it’s like 10 bucks.",
    "There are two kinds of people in this world: those who can count, and me.",
    "Life’s not about waiting for the storm to pass… it’s about hiding from Lois until the storm is over.",
    "Always give 100%, unless you’re giving blood. Then stop at 50%.",
    "The grass isn’t always greener on the other side, unless you’re colorblind, then who knows?",
    "He who laughs last, laughs best. But he who laughs first… probably didn’t get the joke.",
    "If at first you don’t succeed, blame Meg.",
    "Some days you’re the dog, some days you’re the hydrant.",
    "Age is just a number… a big, scary, ever-increasing number.",
    "There are two rules to life: never tell everything you know.",
    "Why be a king when you can be a GriffIN?",
    "Never go to bed angry. Stay up and plot your revenge instead.",
    "You can’t buy happiness, but you can buy beer. Close enough.",
    "Sleep is for the weak... or for when Lois is talking.",
    "Why face your problems when you can just make them laugh with bad jokes?",
    "Never eat the last slice of pizza without making sure Lois isn’t watching.",
    "They say money can’t buy happiness, but it can buy a boat. Same thing.",
    "Life is what happens when you're busy making excuses.",
    "Work hard, nap harder.",
    "Don’t sweat the small stuff… like Meg. Heh heh.",
    "When life knocks you down, just stay there and nap a while."
  ];
  