export interface CommandResponse {
  output: string[];
}

// CoreSystemMessage - A system message that can contain system information
export type CoreSystemMessage = {
  role: 'system';
  content: string;
};

// CoreUserMessage - A user message that can contain text, images, and files
export type CoreUserMessage = {
  role: 'user';
  content: UserContent;
};

export type UserContent = string | Array<TextPart | ImagePart | FilePart>;

// CoreAssistantMessage - An assistant message that contains text, tool calls, or a combination
export type CoreAssistantMessage = {
  role: 'assistant';
  content: AssistantContent;
};

export type AssistantContent = string | Array<TextPart | ToolCallPart>;

// CoreToolMessage - A tool message containing the result of one or more tool calls
export type CoreToolMessage = {
  role: 'tool';
  content: ToolContent;
};

export type ToolContent = Array<ToolResultPart>;

// CoreMessage - A union type for all the different message types
export type CoreMessage =
  | CoreSystemMessage
  | CoreUserMessage
  | CoreAssistantMessage
  | CoreToolMessage;

// CoreMessage Parts

// TextPart - Represents a text content part of a prompt
export interface TextPart {
  type: 'text';
  text: string;
}

// ImagePart - Represents an image part in a user message
export interface ImagePart {
  type: 'image';
  image: DataContent | URL;
  mimeType?: string;
}

// FilePart - Represents a file part in a user message
export interface FilePart {
  type: 'file';
  data: DataContent | URL;
  mimeType: string;
}

// ToolCallPart - Represents a tool call content part, typically generated by the AI model
export interface ToolCallPart {
  type: 'tool-call';
  toolCallId: string;
  toolName: string;
  args: unknown;
}

// ToolResultPart - Represents the result of a tool call in a tool message
export interface ToolResultPart {
  type: 'tool-result';
  toolCallId: string;
  toolName: string;
  result: unknown;
  isError?: boolean;
}

// DataContent - Represents data that can be a base64 string, Uint8Array, ArrayBuffer, or Buffer
export type DataContent = string | Uint8Array | ArrayBuffer | Buffer;
